### ISSUE TITLE
Values freeze after ~10 minutes, then says "Error" in red where exchange is usually displayed.

### ISSUE THREAD

**Issue by gandr003** [taoteh1221/DFD_Crypto_Ticker#1]
Hello! 

Love this build, been using it for a couple weeks now with no problems. Left if off for a few days and once I plugged it back in, the values stopped changing after about 10/15 minutes and then displayed "Error" after a certain amount of time. 

Built using automatic installer on a Raspberry Pi 3A+ and a Hyperpixel Square screen.

**Comment by taoteh1221** [comment]
Hi, glad you enjoy the ticker! :smile: 

The error message you see is when the internet connection on the pi has dropped, or coinbase kicks you off the API connection. It will wait 60 seconds and then attempt to reconnect. 

I've never had issues with coinbase blocking me permanently, so I'm thinking your raspberry pi may have lost it's internet connection? Did you verify it's still connected to the internet ok? It always attempts to reconnect 60 seconds after each failure, so it sounds like the pi doesn't have internet connectivity.

**Comment by gandr003** [comment]
Thanks for the quick response! 

You were absolutely right, was losing connection during a "sleep state," causing the error. 

I seemed to have fixed my pi, one other question! Did you ever get the chance to incorporate any other exchanges? I really want to track NANO but it's on coinbase.com/price/nano, not officially listed on Coinbase, but it's on Binance and Kraken, which you said you might work on. 

Thanks!

**Comment by taoteh1221** [comment]
Glad you got it fixed! :slightly_smiling_face: 

I do have plans to eventually add binance / kraken, but not this week. Maybe next week, as right now I'm sill very busy polishing up a large bug fix release for my Raspberry Pi portfolio tracking app (which you can run on a raspberry pi zero at the same time as the ticker app): https://github.com/taoteh1221/DFD_Cryptocoin_Values/compare/4.14.2...master 

You can add your own favorite coins like nano in that app already, if you want to give it a try (I can help if you get stuck).

I'll let you know when I've added binance and kraken to the ticker. Sorry for the wait, and thanks very much for the feedback on the ticker app, it's much appreciated.

**Comment by taoteh1221** [comment]
@gandr003 I thought you might want a head's up that the Raspberry PI ticker now has support for Binance in the latest version released today (v2.11.0), sorry for the long wait: https://github.com/taoteh1221/DFD_Crypto_Ticker/releases

**Comment by taoteh1221** [comment]
Closing, as there is decent multi-exchange support now.
