### ISSUE TITLE
LCD not working

### ISSUE THREAD

**Issue by finstockpy** [taoteh1221/DFD_Crypto_Ticker#2]
Hi, thanks for creating this

I have a RPI 3 and the LCD was working properly showing the desktop until I ran the installation script

Now I get a black screen at boot that never shows anything

If I log in via VNC I can see the ticker is working properly in the chromium kiosk

Any ideas on what to look for?

Thanks!

**Comment by taoteh1221** [comment]
Did you install the LCD drivers during the ticker auto-install? That may be the problem. You shouldn't do that unless you have a 'goodtft' brand LCD, and know it's model number.

**Comment by finstockpy** [comment]
Thanks

I didn't install the goodtft drivers

Any other ideas?

**Comment by taoteh1221** [comment]
Weird. Do you remember if you chose yes (option 1) in the section: "Do you want to automatically configure DFD Crypto Ticker for your system (autostart at login / keep screen turned on)?" 

If you did have the install script configure auto-start at boot, this installed a system service to auto-start the ticker when your system boots, in this location: /lib/systemd/system/ticker.service

That's the only thing installed to run after boot, except a script running as a cron job every second to keep the screensaver turned off, which installs here: /etc/cron.d/ticker

I doubt the /etc/cron.d/ticker install affects anything, BUT maybe the  /lib/systemd/system/ticker.service install is affecting something on your particular setup, OR you messed up your display drivers / LCD came unplugged and you didn't notice? Have you customized your setup alot, or is it nearly stock? Are you absolutely sure you didn't do something else affecting the display driver install?

Run this command to remove the ticker auto-start service, and see if that helps:
sudo rm  /lib/systemd/system/ticker.service

**Comment by taoteh1221** [comment]
One other thing pretty important to know to solve this: Are you running a recent version of Raspberry Pi OS, or Ubuntu? I've only tested this install script on Raspberry Pi OS, I have no clue if it works on Ubuntu.

**Comment by charona** [comment]
Same here, except I get a white screen. Want to use an old Pi3 Raspiblitz with small screen. When I connect with VNC, I do see the ticker (upside down), but not on the built in screen. So somehow it does its job, but connects to the wrong (VNC) screen, even if I don't connect with VNC.

**Comment by taoteh1221** [comment]
@charona Maybe if you edit the display target in the file /lib/systemd/system/ticker.service, you may be able to get it to use another screen which has been configured. That said, I have no idea how the raspiblitz team provisions their disk image? If you download Raspberry Pi OS Desktop version (not the Lite version, it has unicode issues in chromium), it should work with no issues. 

The screen orientation can be easily changed in config.js in the ticker directory.

**Comment by taoteh1221** [comment]
One other thing folks: There was a bug in v3.00.0, related to the script permissions. I'm not sure that's what's going on here, but make sure you run the LATEST auto-install script again if your version is earlier than v3.00.1 (whatever the last entry is in /DOCUMENTATION-ETC/changelog.txt within your install directory).

You can automatically run the latest install script with this command:
`
wget -O TICKER-INSTALL.bash https://git.io/JU6dw;chmod +x TICKER-INSTALL.bash;sudo ./TICKER-INSTALL.bash
`

**Comment by finstockpy** [comment]
I reinstalled raspberry os and works like a charm now. thanks!

1 more question: how could this be extended to pick up data from cells in googlesheets? . simple read , like here

https://developers.google.com/sheets/api/samples/reading

Thank you!

**Comment by taoteh1221** [comment]
Cool, glad you got it running. Interesting, I'm not sure. Will mark this to look into it whenever I have time. Looks possible.

**Comment by finstockpy** [comment]
great. use case is to have interesting stock metrics of portfolio using googlefinance functions and custom cells and being able to pick them up. looking forward to your thoughts when you have the time. thanks so much!

**Comment by taoteh1221** [comment]
@finstockpy I took a few moments to check out https://developers.google.com/sheets/api/samples/reading per your request. Unfortunately I'm not seeing websocket API support, which is what this ticker app uses (so real-time updates can occur efficiently). Sorry for the bad news.

**Comment by taoteh1221** [comment]
@finstockpy That said, I am looking into https://developers.google.com/sheets/api/samples/reading for portfolio import / export in my portfolio app, now that you've made me aware of it ( https://taoteh1221.github.io  ). Thanks for this info! :)
