### ISSUE TITLE
Currency symbol from auto installation is ₮

### ISSUE THREAD

**Issue by PmanAce** [taoteh1221/DFD_Crypto_Ticker#3]
Currency symbol from auto installation is ₮, how do we change it to $?

**Comment by PmanAce** [comment]
This seems to be the Mongolian currency symbol, which my raspberry pi is not setup as.

**Comment by taoteh1221** [comment]
Hello. It's also the symbol used for USDT (Tether), which is the market your using. There are issues on Raspberry Pi OS Lite with Unicode symbols like this. Try using Raspberry Pi OS Desktop instead, that should solve your issue: https://www.raspberrypi.org/software/operating-systems/

**Comment by PmanAce** [comment]
Ok didn't know, thanks a bunch and thank you for your app, been running it daily!

**Comment by taoteh1221** [comment]
No prob. Your welcome, glad you find it useful! :)
