### ISSUE TITLE
Issues with ADA, BNB, and DOGE

### ISSUE THREAD

**Issue by TMertlich** [taoteh1221/DFD_Crypto_Ticker#4]
Hello,

I just recently installed, and am having issues with some trading pairs.  

On the coinbase side, I am able to pull the prices for BTC-USD, ETH-USD, LINK-USD, and BCH-USD.  I am unable to get prices for ADA-USD, DOGE-USD, and BNB-USD.

On the binance side, I am able to pull the prices for ADA-USDT, DOGE-USDT, and BNB-USDT, but not their USD equivalents.

Thanks,

**Comment by taoteh1221** [comment]
Hello.

For coinbase pro, see if your market exists here (the "id" value): https://api.pro.coinbase.com/products

For binance, see if your market exists here (the "symbol" value, BUT make it LOWERCASE in the ticker config.js settings): https://www.binance.com/api/v3/exchangeInfo

Quickest way to find the coin you want in these data sets is to use "find" feature in your web browser, and just search for the token symbol you want data for.

**Comment by taoteh1221** [comment]
Hope you figured out the proper formatting to use, just holler if your still having trouble. Closing this issue for now.
